###
POST http://{{gateway}}/api/assignments
Content-Type: application/json

{
  "title": "assignment title from api gateway",
  "description": "assignment description from gateway",
  "deadline": "2020-04-30 08:32:23"
}

###
GET http://{{gateway}}/api/assignments/{{assignmentId}}/status

###
PUT http://{{gateway}}/api/assignments/publish/{{assignmentId}}

###
POST http://{{gateway}}/api/submissions
Content-Type: application/json

{
  "code": "printf('hello world');",
  "assignment": "{{assignmentId}}"
}

###
GET http://{{gateway}}/api/submissions
