spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    nacos:
      discovery:
        server-addr: nacos-server:8848
server:
  port: 19999