version: '3'

services:
  gateway-service:
    build: ../assignments-gateway/docker
    image: 'assignments/gateway'
    ports:
      - 19999:19999
    links:
      - submission-service
      - management-service
  management-service:
    build: ../assignments-management/docker
    image: 'assignments/management'
    depends_on:
      - management-mysql
  management-mysql:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: assignments
    ports:
      - 3306:3306
    volumes:
      - ../assignments-management/docker:/docker-entrypoint-initdb.d
  submission-service:
    build: ../assignments-submission/docker
    image: 'assignments/submission'
    depends_on:
      - submission-mysql
  submission-mysql:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: submissions
    ports:
      - 3307:3306
    volumes:
      - ../assignments-submission/docker:/docker-entrypoint-initdb.d
  assignments-ui:
    build: ../assignments-react-ui/docker
    image: 'assignments/react-ui'
    depends_on:
      - gateway-service
    ports:
      - 80:80
