version: '3'

services:
  gateway-service:
    build: ../assignments-gateway/docker
    image: 'assignments/gateway'
    container_name: gateway-service
    ports:
      - 19999:19999
    depends_on:
      - submission-service
      - management-service
  management-service:
    build: ../assignments-management/docker
    image: 'assignments/management'
    container_name: management-service
    depends_on:
      - management-mysql
  management-service02:
    build: ../assignments-management/docker
    image: 'assignments/management'
    container_name: management-service02
    depends_on:
      - management-mysql
  management-mysql:
    image: 'mysql:8'
    container_name: management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: assignments
    volumes:
      - ../assignments-management/docker/schema:/docker-entrypoint-initdb.d
  submission-service:
    build: ../assignments-submission/docker
    image: 'assignments/submission'
    container_name: submission-service
    depends_on:
      - submission-mysql
  submission-mysql:
    image: 'mysql:8'
    container_name: submission-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: submissions
    volumes:
      - ../assignments-submission/docker/schema:/docker-entrypoint-initdb.d
  assignments-ui:
    build: ../assignments-react-ui/docker
    image: 'assignments/react-ui'
    container_name: react-ui
    depends_on:
      - gateway-service
    ports:
      - 80:80

networks:
  default:
    external:
      name: assignments

